trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'

  - script: |
      pip install pandas
      python alert_threshold.py
    displayName: 'Run ELT + Alert Script'
